# Generated by Django 4.2.13 on 2024-06-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentMaster',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=100)),
            ],
        ),
    ]
